#!/usr/bin/env bash
cd tekvideo.sdu.dk
git pull
chmod +x grailsw
./grailsw war
mv build/libs/*.war ../tekvideo.war
cd ..
cp tekvideo.war `date +'tekvideo%Y-%m-%d_%H.%M.%S.war'`
sudo mv tekvideo.war /var/lib/tomcat9/webapps/ROOT.war
sudo chown tomcat: /var/lib/tomcat9/webapps/ROOT.war
sudo tail -f `date +'/var/lib/tomcat9/logs/catalina.%Y-%m-%d.log'`
